In [ ]:
import pandas as pd
import numpy as np

df= pd.read_csv(r"C:\Users\Prajwal\OneDrive\Desktop\codveda data analysis task\data\raw\2) Stock Prices Data Set.csv")

df['daily_return'] = df.groupby('symbol')['close price'].pct_change()  #grouop by is used to divide the data based on each stock symbol before calculating the percentage change in closing prices.
df.head()

,symbol,date,open price,high price,low price,close price,volume traded,daily_return
0,AAL,02-01-2014,25.0700,25.8200,25.0600,25.3600,8998943,NaN
1,AAPL,02-01-2014,79.3828,79.5756,78.8601,79.0185,58791957,NaN
2,AAP,02-01-2014,110.3600,111.8800,109.2900,109.7400,542711,NaN
3,ABBV,02-01-2014,52.1200,52.3300,51.5200,51.9800,4569061,NaN
4,ABC,02-01-2014,70.1100,70.2300,69.4800,69.8900,1148391,NaN

In [7]:
df['price_range'] = df['high price'] - df['low price']
df.head(10)

,symbol,date,open price,high price,low price,close price,volume traded,daily_return,price_range
0,AAL,02-01-2014,25.0700,25.8200,25.0600,25.3600,8998943,NaN,0.7600
1,AAPL,02-01-2014,79.3828,79.5756,78.8601,79.0185,58791957,NaN,0.7155
2,AAP,02-01-2014,110.3600,111.8800,109.2900,109.7400,542711,NaN,2.5900
3,ABBV,02-01-2014,52.1200,52.3300,51.5200,51.9800,4569061,NaN,0.8100
4,ABC,02-01-2014,70.1100,70.2300,69.4800,69.8900,1148391,NaN,0.7500
5,ABT,02-01-2014,38.0900,38.4000,38.0000,38.2300,4967472,NaN,0.4000
6,ACN,02-01-2014,81.5000,81.9200,81.0900,81.1300,2405384,NaN,0.8300
7,ADBE,02-01-2014,59.0600,59.5300,58.9400,59.2900,2746370,NaN,0.5900
8,ADI,02-01-2014,49.5200,49.7500,49.0400,49.2800,2799092,NaN,0.7100
9,ADM,02-01-2014,43.2200,43.2900,42.7900,42.9900,2753765,NaN,0.5000

In [8]:
df['ma10'] = df.groupby('symbol')['close price'].transform(lambda x: x.rolling(10).mean())
df.head()

,symbol,date,open price,high price,low price,close price,volume traded,daily_return,price_range,ma10
0,AAL,02-01-2014,25.0700,25.8200,25.0600,25.3600,8998943,NaN,0.7600,NaN
1,AAPL,02-01-2014,79.3828,79.5756,78.8601,79.0185,58791957,NaN,0.7155,NaN
2,AAP,02-01-2014,110.3600,111.8800,109.2900,109.7400,542711,NaN,2.5900,NaN
3,ABBV,02-01-2014,52.1200,52.3300,51.5200,51.9800,4569061,NaN,0.8100,NaN
4,ABC,02-01-2014,70.1100,70.2300,69.4800,69.8900,1148391,NaN,0.7500,NaN

In [9]:
df['volatility_10'] = df.groupby('symbol')['daily_return'].transform(lambda x: x.rolling(10).std())
df.head()

,symbol,date,open price,high price,low price,close price,volume traded,daily_return,price_range,ma10,volatility_10
0,AAL,02-01-2014,25.0700,25.8200,25.0600,25.3600,8998943,NaN,0.7600,NaN,NaN
1,AAPL,02-01-2014,79.3828,79.5756,78.8601,79.0185,58791957,NaN,0.7155,NaN,NaN
2,AAP,02-01-2014,110.3600,111.8800,109.2900,109.7400,542711,NaN,2.5900,NaN,NaN
3,ABBV,02-01-2014,52.1200,52.3300,51.5200,51.9800,4569061,NaN,0.8100,NaN,NaN
4,ABC,02-01-2014,70.1100,70.2300,69.4800,69.8900,1148391,NaN,0.7500,NaN,NaN